spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  kafka:
    bootstrap-servers: localhost:29092
springdoc:
  swagger-ui:
    path: /coffee/swagger-ui.html
  api-docs:
    path: /coffee/api-docs
server:
  error:
    include-message: always
  port: 8080
grpc:
  server:
    port: 8090
